configure: detecting numarray, printing summary information

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21813,7 +21813,7 @@ fi
 
 if test "x$with_fftw" = "x"; then
   with_fftw=no
-  echo "FFTW lib not explicitely enabled. Using GSL version for FFT."
+  #echo "FFTW lib not explicitely enabled. Using GSL version for FFT."
 fi
 
 if test "x$with_fftw" != "xno"; then
@@ -22014,7 +22014,7 @@ fi
 
 if test "x$with_libproj4" = "x"; then
   with_libproj4=no
-  echo "LIBPROJ4 lib not explicitely enabled. Map projection routines not supported."
+#  echo "LIBPROJ4 lib not explicitely enabled. Map projection routines not supported."
 fi
 
 if test "x$with_libproj4" != "xno"; then
@@ -22383,34 +22383,35 @@ fi
 
 if test "x$with_python" != "xno"; then
 
-# Check whether --enable-python_version was given.
+    # Check whether --enable-python_version was given.
 if test "${enable_python_version+set}" = set; then
   enableval=$enable_python_version;  PYTHON_VERSION="$enableval"
 
 fi
 
 
-if test "x$PYTHON_VERSION" = "x"; then
-
-   echo -n "Automatic determination of python version."
-
-   queryfile=$ac_confdir/query_version.py
-   echo # tmp file auto (re)generated by GDL configure. Please delete > $queryfile
-   echo import sys >> $queryfile
-   echo print \'%s.%s\' % sys.version_info\[0:2\] >> $queryfile
-
-  PYTHON_VERSION=`python $queryfile`
-   rm $queryfile
-fi
+  if test "x$PYTHON_VERSION" = "x"; then
+    { $as_echo "$as_me:$LINENO: checking for Python version" >&5
+$as_echo_n "checking for Python version... " >&6; }
+    queryfile=$ac_confdir/query_version.py
+    echo "# tmp file auto (re)generated by GDL configure. Please delete" > $queryfile
+    echo import sys >> $queryfile
+    echo print \'%s.%s\' % sys.version_info\[0:2\] >> $queryfile
+    PYTHON_VERSION=`python $queryfile`
+    rm $queryfile
+    { $as_echo "$as_me:$LINENO: result: $PYTHON_VERSION" >&5
+$as_echo "$PYTHON_VERSION" >&6; }
+  fi
 
   if test "x$with_python" != "xyes"; then
     LIBS="$LIBS -L$with_python/lib"
     LIBS="$LIBS -L$with_python/lib/python$PYTHON_VERSION/config -lpython$PYTHON_VERSION"
-    INCLUDES="$INCLUDES -I$with_python/include/python$PYTHON_VERSION"
+    PYTHON_INCLUDES="$with_python/include/python$PYTHON_VERSION"
   else
     LIBS="$LIBS -lpython$PYTHON_VERSION"
-    INCLUDES="$INCLUDES -I/usr/include/python$PYTHON_VERSION"
+    PYTHON_INCLUDES="/usr/include/python$PYTHON_VERSION"
   fi
+  INCLUDES="$INCLUDES -I$PYTHON_INCLUDES"
 
   as_ac_Lib=`$as_echo "ac_cv_lib_python$PYTHON_VERSION''_Py_Initialize" | $as_tr_sh`
 { $as_echo "$as_me:$LINENO: checking for Py_Initialize in -lpython$PYTHON_VERSION" >&5
@@ -22498,6 +22499,215 @@ else
 
 fi
 
+
+  as_ac_Header=`$as_echo "ac_cv_header_$PYTHON_INCLUDES/Python.h" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { $as_echo "$as_me:$LINENO: checking for $PYTHON_INCLUDES/Python.h" >&5
+$as_echo_n "checking for $PYTHON_INCLUDES/Python.h... " >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  $as_echo_n "(cached) " >&6
+fi
+ac_res=`eval 'as_val=${'$as_ac_Header'}
+		 $as_echo "$as_val"'`
+	       { $as_echo "$as_me:$LINENO: result: $ac_res" >&5
+$as_echo "$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ $as_echo "$as_me:$LINENO: checking $PYTHON_INCLUDES/Python.h usability" >&5
+$as_echo_n "checking $PYTHON_INCLUDES/Python.h usability... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$PYTHON_INCLUDES/Python.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ $as_echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+$as_echo "$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ $as_echo "$as_me:$LINENO: checking $PYTHON_INCLUDES/Python.h presence" >&5
+$as_echo_n "checking $PYTHON_INCLUDES/Python.h presence... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$PYTHON_INCLUDES/Python.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ $as_echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+$as_echo "$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { $as_echo "$as_me:$LINENO: WARNING: $PYTHON_INCLUDES/Python.h: accepted by the compiler, rejected by the preprocessor!" >&5
+$as_echo "$as_me: WARNING: $PYTHON_INCLUDES/Python.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: $PYTHON_INCLUDES/Python.h: proceeding with the compiler's result" >&5
+$as_echo "$as_me: WARNING: $PYTHON_INCLUDES/Python.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { $as_echo "$as_me:$LINENO: WARNING: $PYTHON_INCLUDES/Python.h: present but cannot be compiled" >&5
+$as_echo "$as_me: WARNING: $PYTHON_INCLUDES/Python.h: present but cannot be compiled" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: $PYTHON_INCLUDES/Python.h:     check for missing prerequisite headers?" >&5
+$as_echo "$as_me: WARNING: $PYTHON_INCLUDES/Python.h:     check for missing prerequisite headers?" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: $PYTHON_INCLUDES/Python.h: see the Autoconf documentation" >&5
+$as_echo "$as_me: WARNING: $PYTHON_INCLUDES/Python.h: see the Autoconf documentation" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: $PYTHON_INCLUDES/Python.h:     section \"Present But Cannot Be Compiled\"" >&5
+$as_echo "$as_me: WARNING: $PYTHON_INCLUDES/Python.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: $PYTHON_INCLUDES/Python.h: proceeding with the preprocessor's result" >&5
+$as_echo "$as_me: WARNING: $PYTHON_INCLUDES/Python.h: proceeding with the preprocessor's result" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: $PYTHON_INCLUDES/Python.h: in the future, the compiler will take precedence" >&5
+$as_echo "$as_me: WARNING: $PYTHON_INCLUDES/Python.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ $as_echo "$as_me:$LINENO: checking for $PYTHON_INCLUDES/Python.h" >&5
+$as_echo_n "checking for $PYTHON_INCLUDES/Python.h... " >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  $as_echo_n "(cached) " >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval 'as_val=${'$as_ac_Header'}
+		 $as_echo "$as_val"'`
+	       { $as_echo "$as_me:$LINENO: result: $ac_res" >&5
+$as_echo "$ac_res" >&6; }
+
+fi
+if test `eval 'as_val=${'$as_ac_Header'}
+		 $as_echo "$as_val"'` = yes; then
+  :
+else
+
+    echo ""
+    echo "Error! Python header file not found (missing '-devel' package?)"
+    echo "  Use --with-python=no to disable Python support"
+    exit -1
+
+fi
+
+
+
+  as_ac_Header=`$as_echo "ac_cv_header_$PYTHON_INCLUDES/numarray/libnumarray.h" | $as_tr_sh`
+{ $as_echo "$as_me:$LINENO: checking for $PYTHON_INCLUDES/numarray/libnumarray.h" >&5
+$as_echo_n "checking for $PYTHON_INCLUDES/numarray/libnumarray.h... " >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  $as_echo_n "(cached) " >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$PYTHON_INCLUDES/Python.h>
+
+#include <$PYTHON_INCLUDES/numarray/libnumarray.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  eval "$as_ac_Header=yes"
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	eval "$as_ac_Header=no"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+ac_res=`eval 'as_val=${'$as_ac_Header'}
+		 $as_echo "$as_val"'`
+	       { $as_echo "$as_me:$LINENO: result: $ac_res" >&5
+$as_echo "$ac_res" >&6; }
+if test `eval 'as_val=${'$as_ac_Header'}
+		 $as_echo "$as_val"'` = yes; then
+  :
+else
+
+    echo ""
+    echo "Error! Python numarray package was not found"
+    echo "  Use --with-python=no to disable Python support"
+    exit -1
+
+fi
+
+
+
 fi
 
 
@@ -22521,8 +22731,6 @@ _ACEOF
   test "$exec_prefix_NONE" && exec_prefix=NONE
 
 #AC_DEFINE([EXEC_PREFIX],[\"`echo ${exec_prefix}`\"],[GDL installation directory])
-
-echo System is:  ${host}
 
 DARWIN="no"
 
@@ -24189,3 +24397,39 @@ $as_echo "$as_me: WARNING: Unrecognized options: $ac_unrecognized_opts" >&2;}
 fi
 
 
+echo "
+                  GDL - GNU Data Language
+  ----- compilation options: ---------------------------
+  System:              $host
+  Installation prefix: $prefix
+  C++ compiler:        $CXX $CXXFLAGS
+  ----- optional libraries (consult README/INSTALL): ---
+  wxWidgets:           `if test no = $with_wxWidgets;
+    then echo 'no  (needs explicit enabling)'; else echo yes; fi`
+  Magick:              `if test no = $with_Magick;
+    then echo 'no'; else echo yes; fi`
+  NetCDF:              `if test no = $with_netcdf;
+    then echo 'no'; else echo yes; fi`
+  HDF4:                `if test no = $with_hdf;
+    then echo 'no'; else echo yes; fi`
+  HDF5:                `if test no = $with_hdf5;
+    then echo 'no'; else echo yes; fi`
+  FFTW:                `if test no = $with_fftw;
+    then echo 'no  (GSL version used by default)'; else echo yes; fi`
+  libproject:          `if test no = $with_libproj4;
+    then echo 'no  (see also MAP_INSTALL)'; else echo yes; fi`
+  MPICH:               `if test no = $with_mpich;
+    then echo 'no  (needs explicit enabling)'; else echo yes; fi`
+  Python:              `if test no = $with_python;
+    then echo 'no  (see also PYTHON.txt)'; else echo yes; fi`
+  ----- notes on auxiliary files: ----------------------
+  - routines implemented in GDL are located in src/pro/,
+    use GDL_PATH env. variable to inform GDL about their
+    location (files not installed by 'make install')
+  - consult MAP_INSTALL for details concerning auxiliary
+    files needed for mapping support
+  - SAVE and RESTORE procedures require *.pro files from
+    the CMSVLIB package (see README for details)
+  ------------------------------------------------------
+  use 'make' to build and 'make install' to install GDL
+"
