determining ImageMagick flags using Magick++-config (tracker entry no 1963366)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -873,6 +873,7 @@ LIBTOOL
 HAVE_64BIT_OS
 BUILDASLIBRARY_TRUE
 BUILDASLIBRARY_FALSE
+MagickConfig
 EXEC_PREFIX
 DARWIN_TRUE
 DARWIN_FALSE
@@ -4815,7 +4816,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4818 "configure"' > conftest.$ac_ext
+  echo '#line 4819 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7394,11 +7395,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7397: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7398: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7401: \$? = $ac_status" >&5
+   echo "$as_me:7402: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7684,11 +7685,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7687: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7688: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7691: \$? = $ac_status" >&5
+   echo "$as_me:7692: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7788,11 +7789,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7791: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7792: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7795: \$? = $ac_status" >&5
+   echo "$as_me:7796: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10165,7 +10166,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10168 "configure"
+#line 10169 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10265,7 +10266,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10268 "configure"
+#line 10269 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12666,11 +12667,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12669: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12670: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12673: \$? = $ac_status" >&5
+   echo "$as_me:12674: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12770,11 +12771,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12773: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12774: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12777: \$? = $ac_status" >&5
+   echo "$as_me:12778: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14368,11 +14369,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14371: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14372: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14375: \$? = $ac_status" >&5
+   echo "$as_me:14376: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14472,11 +14473,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14475: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14476: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14479: \$? = $ac_status" >&5
+   echo "$as_me:14480: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16692,11 +16693,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16695: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16696: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16699: \$? = $ac_status" >&5
+   echo "$as_me:16700: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16982,11 +16983,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16985: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16986: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16989: \$? = $ac_status" >&5
+   echo "$as_me:16990: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17086,11 +17087,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17089: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17090: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17093: \$? = $ac_status" >&5
+   echo "$as_me:17094: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20650,21 +20651,114 @@ if test "x$with_Magick" = "x"; then
 fi
 
 if test "x$with_Magick" != "xno"; then
-  if test "x$with_Magick" != "xyes"; then
-    LIBS="$LIBS -L$with_Magick/lib -lMagick++"
-    INCLUDES="$INCLUDES -I$with_Magick/include"
+  if test "x$with_Magick" = "xyes"; then
+    # Extract the first word of "Magick++-config", so it can be a program name with args.
+set dummy Magick++-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_MagickConfig+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MagickConfig in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MagickConfig="$MagickConfig" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_MagickConfig="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_MagickConfig" && ac_cv_path_MagickConfig="no"
+  ;;
+esac
+fi
+MagickConfig=$ac_cv_path_MagickConfig
+if test -n "$MagickConfig"; then
+  { echo "$as_me:$LINENO: result: $MagickConfig" >&5
+echo "${ECHO_T}$MagickConfig" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
   else
-    LIBS="$LIBS -lMagick++"
-    INCLUDES="$INCLUDES -I/usr/include/magick"
+    # Extract the first word of "Magick++-config", so it can be a program name with args.
+set dummy Magick++-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_MagickConfig+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MagickConfig in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MagickConfig="$MagickConfig" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in "$with_Magick/bin"
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_MagickConfig="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_MagickConfig" && ac_cv_path_MagickConfig="no"
+  ;;
+esac
+fi
+MagickConfig=$ac_cv_path_MagickConfig
+if test -n "$MagickConfig"; then
+  { echo "$as_me:$LINENO: result: $MagickConfig" >&5
+echo "${ECHO_T}$MagickConfig" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
   fi
 
-  { echo "$as_me:$LINENO: checking for GetMagickVersion in -lMagick" >&5
-echo $ECHO_N "checking for GetMagickVersion in -lMagick... $ECHO_C" >&6; }
-if test "${ac_cv_lib_Magick_GetMagickVersion+set}" = set; then
+  if test "x$MagickConfig" = "xno"; then
+    { { echo "$as_me:$LINENO: error: ImageMagick is required but was not found (Magick++-config program not found)
+      Use --with-Magick=DIR to specify the ImageMagick directory tree
+      Use --with-Magick=no  to not use it
+    " >&5
+echo "$as_me: error: ImageMagick is required but was not found (Magick++-config program not found)
+      Use --with-Magick=DIR to specify the ImageMagick directory tree
+      Use --with-Magick=no  to not use it
+    " >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    LIBS="$LIBS `$MagickConfig --libs`"
+    INCLUDES="$INCLUDES `$MagickConfig --cppflags`"
+  fi
+
+  { echo "$as_me:$LINENO: checking for GetMagickVersion in -lMagick++" >&5
+echo $ECHO_N "checking for GetMagickVersion in -lMagick++... $ECHO_C" >&6; }
+if test "${ac_cv_lib_Magickpp_GetMagickVersion+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lMagick  $LIBS"
+LIBS="-lMagick++  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -20705,21 +20799,21 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_Magick_GetMagickVersion=yes
+  ac_cv_lib_Magickpp_GetMagickVersion=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_Magick_GetMagickVersion=no
+	ac_cv_lib_Magickpp_GetMagickVersion=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_Magick_GetMagickVersion" >&5
-echo "${ECHO_T}$ac_cv_lib_Magick_GetMagickVersion" >&6; }
-if test $ac_cv_lib_Magick_GetMagickVersion = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_Magickpp_GetMagickVersion" >&5
+echo "${ECHO_T}$ac_cv_lib_Magickpp_GetMagickVersion" >&6; }
+if test $ac_cv_lib_Magickpp_GetMagickVersion = yes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_MAGICK 1
@@ -21796,6 +21890,7 @@ fi
 
 
 
+
   prefix_NONE=
   exec_prefix_NONE=
   test "x$prefix" = xNONE && prefix_NONE=yes && prefix=$ac_default_prefix
@@ -22823,6 +22918,7 @@ LIBTOOL!$LIBTOOL$ac_delim
 HAVE_64BIT_OS!$HAVE_64BIT_OS$ac_delim
 BUILDASLIBRARY_TRUE!$BUILDASLIBRARY_TRUE$ac_delim
 BUILDASLIBRARY_FALSE!$BUILDASLIBRARY_FALSE$ac_delim
+MagickConfig!$MagickConfig$ac_delim
 EXEC_PREFIX!$EXEC_PREFIX$ac_delim
 DARWIN_TRUE!$DARWIN_TRUE$ac_delim
 DARWIN_FALSE!$DARWIN_FALSE$ac_delim
@@ -22832,7 +22928,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 17; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 18; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
