stride index support ([n:n:n])

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1034,6 +1034,7 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-python_module  make GDL python module (default: standalone version)
+  --enable-python_version  set explicit python version to use (eg. 2.4)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1044,7 +1045,7 @@ Optional Packages:
   --with-tags[=TAGS]
                           include additional configurations [automatic]
   --with-ncursesdir=DIR   specify the ncurses directory tree
-  --with-readlinedir=DIR  specify the readline directory tree
+  --with-readlinedir=DIR  specify the GNU readline directory tree
   --with-gsldir=DIR       specify the GSL directory tree
   --with-plplotdir=DIR    specify the plplot directory tree
   --with-Magick=DIR       use ImageMagick package (with optional path DIR)
@@ -4138,7 +4139,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4141 "configure"' > conftest.$ac_ext
+  echo '#line 4142 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5246,7 +5247,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5249:" \
+echo "$as_me:5250:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6280,11 +6281,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6283: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6284: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6287: \$? = $ac_status" >&5
+   echo "$as_me:6288: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6513,11 +6514,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6516: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6517: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6520: \$? = $ac_status" >&5
+   echo "$as_me:6521: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6573,11 +6574,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6576: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6577: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6580: \$? = $ac_status" >&5
+   echo "$as_me:6581: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7907,7 +7908,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 7910 "configure"' > conftest.$ac_ext
+    echo '#line 7911 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8778,7 +8779,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8781 "configure"
+#line 8782 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8876,7 +8877,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8879 "configure"
+#line 8880 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11055,11 +11056,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11058: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11059: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11062: \$? = $ac_status" >&5
+   echo "$as_me:11063: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11115,11 +11116,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11118: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11119: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11122: \$? = $ac_status" >&5
+   echo "$as_me:11123: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11626,7 +11627,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 11629 "configure"' > conftest.$ac_ext
+    echo '#line 11630 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12497,7 +12498,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12500 "configure"
+#line 12501 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12595,7 +12596,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12598 "configure"
+#line 12599 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13422,11 +13423,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13425: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13426: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13429: \$? = $ac_status" >&5
+   echo "$as_me:13430: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13482,11 +13483,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13485: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13486: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13489: \$? = $ac_status" >&5
+   echo "$as_me:13490: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14796,7 +14797,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 14799 "configure"' > conftest.$ac_ext
+    echo '#line 14800 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15537,11 +15538,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15540: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15541: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15544: \$? = $ac_status" >&5
+   echo "$as_me:15545: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15770,11 +15771,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15773: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15774: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15777: \$? = $ac_status" >&5
+   echo "$as_me:15778: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15830,11 +15831,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15833: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15834: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15837: \$? = $ac_status" >&5
+   echo "$as_me:15838: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17164,7 +17165,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 17167 "configure"' > conftest.$ac_ext
+    echo '#line 17168 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18035,7 +18036,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18038 "configure"
+#line 18039 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18133,7 +18134,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18136 "configure"
+#line 18137 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19177,19 +19178,9 @@ fi
 
 
 
-
 # Check whether --with-ncursesdir or --without-ncursesdir was given.
 if test "${with_ncursesdir+set}" = set; then
   withval="$with_ncursesdir"
-   LIBS="$LIBS -L$withval/lib"
-         INCLUDES="$INCLUDES -I$withval/include"
-
-fi;
-
-
-# Check whether --with-readlinedir or --without-readlinedir was given.
-if test "${with_readlinedir+set}" = set; then
-  withval="$with_readlinedir"
    LIBS="$LIBS -L$withval/lib"
          INCLUDES="$INCLUDES -I$withval/include"
 
@@ -19270,9 +19261,31 @@ _ACEOF
 fi
 
 
-echo "$as_me:$LINENO: checking for readline in -lreadline" >&5
-echo $ECHO_N "checking for readline in -lreadline... $ECHO_C" >&6
-if test "${ac_cv_lib_readline_readline+set}" = set; then
+
+
+
+# Check whether --with-readlinedir or --without-readlinedir was given.
+if test "${with_readlinedir+set}" = set; then
+  withval="$with_readlinedir"
+   with_readlinedir="$withval"
+fi;
+
+if test "x$with_readlinedir" = "x"; then
+  with_readlinedir=yes
+fi
+
+if test "x$with_readlinedir" != "xno"; then
+
+  if test "x$with_readlinedir" != "xyes"; then
+    LIBS="-L$with_readlinedir/lib $LIBS -lreadline"
+    INCLUDES="$INCLUDES -I$with_readlinedir/include"
+  else
+    LIBS="$LIBS -lreadline"
+  fi
+
+  echo "$as_me:$LINENO: checking for stifle_history in -lreadline" >&5
+echo $ECHO_N "checking for stifle_history in -lreadline... $ECHO_C" >&6
+if test "${ac_cv_lib_readline_stifle_history+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
@@ -19290,11 +19303,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char readline ();
+char stifle_history ();
 int
 main ()
 {
-readline ();
+stifle_history ();
   ;
   return 0;
 }
@@ -19321,27 +19334,39 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_readline_readline=yes
+  ac_cv_lib_readline_stifle_history=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_readline_readline=no
+ac_cv_lib_readline_stifle_history=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_readline_readline" >&5
-echo "${ECHO_T}$ac_cv_lib_readline_readline" >&6
-if test $ac_cv_lib_readline_readline = yes; then
-  cat >>confdefs.h <<_ACEOF
+echo "$as_me:$LINENO: result: $ac_cv_lib_readline_stifle_history" >&5
+echo "${ECHO_T}$ac_cv_lib_readline_stifle_history" >&6
+if test $ac_cv_lib_readline_stifle_history = yes; then
+
+
+cat >>confdefs.h <<\_ACEOF
 #define HAVE_LIBREADLINE 1
 _ACEOF
 
-  LIBS="-lreadline $LIBS"
+else
+
+	echo ""
+	echo "Error! GNU readline was not found."
+	echo "       Use --with-readlinedir=no to expicitely disable it"
+	echo "       Check the README or use configure --help for other libraries needed"
+
+	exit -1
 
 fi
+
+fi
+
 
 
 
@@ -20141,8 +20166,6 @@ fi
 
 fi
 
-PYTHON_VERSION="2.3"
-
 
 # Check whether --with-python or --without-python was given.
 if test "${with_python+set}" = set; then
@@ -20155,6 +20178,26 @@ if test "x$with_python" = "x"; then
 fi
 
 if test "x$with_python" != "xno"; then
+
+# Check whether --enable-python_version or --disable-python_version was given.
+if test "${enable_python_version+set}" = set; then
+  enableval="$enable_python_version"
+   PYTHON_VERSION="$enableval"
+
+fi;
+
+if test "x$PYTHON_VERSION" == "x"; then
+
+   echo -n "Automatic determination of python version."
+
+   queryfile=$ac_confdir/query_version.py
+   echo # tmp file auto (re)generated by GDL configure. Please delete > $queryfile
+   echo import sys >> $queryfile
+   echo print sys.version.split\(\'.\'\)\[0\]+\".\"+sys.version.split\(\'.\'\)\[1\] >> $queryfile
+   PYTHON_VERSION=`python $queryfile`
+   rm $queryfile
+fi
+
   if test "x$with_python" != "xyes"; then
     LIBS="$LIBS -L$with_python/lib"     LIBS="$LIBS -L$with_python/lib/python$PYTHON_VERSION/config -lpython$PYTHON_VERSION"
     INCLUDES="$INCLUDES -I$with_python/include/python$PYTHON_VERSION"
