More precise error message for '@'

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19371,6 +19371,98 @@ fi
 
 
 
+if test "x$with_wxWidgets" == "x"; then
+   with_wxWidgets=no
+fi
+
+if test "x$with_wxWidgets" != "xno"; then
+	LIBS="$LIBS `wx-config --libs`"
+	INCLUDES="$INCLUDES `wx-config --cxxflags`"
+	LIBS="$LIBS `wx-config --libs` `wx-config --cxxflags`"
+	echo "$as_me:$LINENO: checking for _Z12wxInitializeiPPc in -lwx_base-2.6" >&5
+echo $ECHO_N "checking for _Z12wxInitializeiPPc in -lwx_base-2.6... $ECHO_C" >&6
+if test "${ac_cv_lib_wx_base_2_6__Z12wxInitializeiPPc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lwx_base-2.6  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char _Z12wxInitializeiPPc ();
+int
+main ()
+{
+_Z12wxInitializeiPPc ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_wx_base_2_6__Z12wxInitializeiPPc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_wx_base_2_6__Z12wxInitializeiPPc=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_wx_base_2_6__Z12wxInitializeiPPc" >&5
+echo "${ECHO_T}$ac_cv_lib_wx_base_2_6__Z12wxInitializeiPPc" >&6
+if test $ac_cv_lib_wx_base_2_6__Z12wxInitializeiPPc = yes; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LIBWXWIDGETS 1
+_ACEOF
+
+
+else
+
+	echo ""
+	echo "Error! You must have wxWidgets library 2.6 installed"
+	echo "       Use --with-wxWidgets=no to expicitely disable it"
+	echo "       Check the README or use configure --help for other libraries needed"
+     echo "       (--with-xxxdir = obligatory, --with-xxx = optional (--with-xxx=no to disable))"
+	exit -1
+
+fi
+
+fi
 
 
 
