doc/udg updates (EXECUTE + fixes in makeall)

diff --git a/doc/udg/makeall b/doc/udg/makeall
--- a/doc/udg/makeall
+++ b/doc/udg/makeall
@@ -19,7 +19,7 @@
 echo -n "--- Generating routinelist.tmp file (may take a while) ... "
 newest=`ls -1 -t ../../src/pro/*.pro ../../src/gdl ./gdl.pro ./routinelist.pro | head -1`
 if `test ! -e routinelist.tmp` || `test $newest -nt routinelist.tmp`; then
-  ../../src/gdl -quiet -e "routinelist, 'routinelist.tmp'" 2>/dev/stdout 1>routinelist.log;
+  ../../src/gdl -quiet -e "routinelist, 'routinelist.tmp'" &>routinelist.log;
   if `test 0 -eq $?`; then
     echo "done";
   else
@@ -61,7 +61,7 @@ for i in `cd examples; find * -type d -and ! -name CVS`; do
   newest=`ls -1 -t ../../src/pro/*.pro ../../src/gdl examples/_pre examples/_post examples/$i/$i.pro | head -1`
   if `test ! -e examples/$i/$i.out.txt` || `test $newest -nt examples/$i/$i.out.txt`; then
     cd examples/$i
-    IDL_PATH= GDL_PATH=+../../../../src/pro ../../../../src/gdl -quiet ../_pre $i.pro ../_post 2>/dev/stdout 1>$i.out.txt.tmp; 
+    IDL_PATH= GDL_PATH=+../../../../src/pro ../../../../src/gdl -quiet ../_pre $i.pro ../_post &>$i.out.txt.tmp; 
     cd ../..
     tail -`wc -l examples/$i/$i.out.txt.tmp | awk '{print $1-1}'` examples/$i/$i.out.txt.tmp > examples/$i/$i.out.txt
     rm examples/$i/$i.out.txt.tmp
@@ -74,7 +74,7 @@ for i in `cd examples; find * -type d -and ! -name CVS`; do
     touch examples/$i/$i.out.tex # TODO: czy to jest potrzebne?
     if test -e examples/$i/gdl.ps; then 
       echo -n "--- Regenerating example plot file $i.out.pdf ... "
-      ps2pdf examples/$i/gdl.ps examples/$i/$i.out.pdf 1>/dev/stderr 2>ps2pdf.log
+      ps2pdf examples/$i/gdl.ps examples/$i/$i.out.pdf &>ps2pdf.log
       if `test 0 -eq $?`; then
         echo "done"
       else
@@ -83,7 +83,7 @@ for i in `cd examples; find * -type d -and ! -name CVS`; do
       fi
       rm examples/$i/gdl.ps
       echo -n "--- Cropping $i.out.pdf ... "
-      pdfcrop examples/$i/$i.out.pdf 2>/dev/stdout 1>pdfcrop.log
+      pdfcrop examples/$i/$i.out.pdf &>pdfcrop.log
       if `test 0 -eq $?`; then
         echo "done"
       else
@@ -102,7 +102,7 @@ done
 
 # doing LaTeX 1st pass
 echo -n "--- Doing LaTeX 1-st pass (generating gdl.aux, gdl.idx and gdl.out files - this takes a while) ... "
-pdflatex -draftmode -halt-on-error gdl.tex 2>/dev/stdout 1>pdflatex.log
+pdflatex -draftmode -halt-on-error gdl.tex &>pdflatex.log
 if `test 0 -eq $?`; then
   echo "done";
 else
@@ -112,7 +112,7 @@ fi
 
 # running BiBTeX
 echo -n "--- Running BiBTeX (generating gdl.bbl) ..."
-bibtex gdl 2>/dev/stdout 1>bibtex.log
+bibtex gdl &>bibtex.log
 if `test 0 -eq $?`; then
   echo "done";
 else
@@ -125,7 +125,7 @@ fgrep Warning bibtex.log > diag/broken-references
 
 # doing LaTeX 2nd pass
 echo -n "--- Doing LaTeX 2-nd pass (generating gdl.pdf - this takes a while) ... "
-pdflatex -halt-on-error gdl.tex 2>/dev/stdout 1>pdflatex.log
+pdflatex -halt-on-error gdl.tex &>pdflatex.log
 if `test 0 -eq $?`; then
   echo "done";
 else
@@ -135,7 +135,7 @@ fi
 
 # running authorindex
 echo -n "--- Running authorindex (generating gdl.ain) ..."
-authorindex gdl 1>/dev/stderr 2>authorindex.log
+authorindex gdl &>authorindex.log
 if `test 0 -eq $?`; then
   echo "done";
 else
@@ -145,7 +145,7 @@ fi
 
 # running makeindex
 echo -n "--- Running makeindex (generating gdl.ind) ... "
-makeindex gdl 1>/dev/stderr 2>makeindex.log
+makeindex gdl &>makeindex.log
 if `test 0 -eq $?`; then
   echo "done";
 else
@@ -154,13 +154,23 @@ else
 fi
 
 # doing LaTeX 3rd pass
-echo -n "--- Doing LaTeX 3-rd pass (correcting references in gdl.pdf - this takes a while) ... "
-pdflatex -halt-on-error gdl.tex 2>/dev/stdout 1>pdflatex.log
+echo -n "--- Doing LaTeX 3-rd pass (that should give a final gdl.aux file - this takes a while) ... "
+pdflatex -halt-on-error gdl.tex &>pdflatex.log
 if `test 0 -eq $?`; then
   echo "done";
 else
   echo "error (consult pdflatex.log)";
   exit 1
 fi
+
+## doing LaTeX 3rd pass
+#echo -n "--- Doing LaTeX 4-th pass (that should give a final gdl.pdf file - this takes a while) ... "
+#pdflatex -halt-on-error gdl.tex &>pdflatex.log
+#if `test 0 -eq $?`; then
+#  echo "done";
+#else
+#  echo "error (consult pdflatex.log)";
+#  exit 1
+#fi
 
 #  fgrep -1 warning gdl.log             # re-outputing warnings
